# Generated by Django 5.2.17 on 2026-08-16 08:37

import apps.chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=apps.chat.models.new_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('environment', models.CharField(default='production', max_length=40)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_hint', models.CharField(max_length=20)),
                ('key_rotated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
