# Generated by Django 5.2.17 on 2026-08-16 08:37

import apps.chat.models
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.CharField(default=apps.chat.models.new_ulid, editable=False, max_length=26, primary_key=True, serialize=False)),
                ('generation_id', models.CharField(max_length=64, unique=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=200)),
                ('trace_id', models.CharField(blank=True, default='', max_length=64)),
                ('project_id', models.CharField(db_index=True, max_length=26)),
                ('end_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'Openai'), ('gcp.gemini', 'Gemini'), ('groq', 'Groq'), ('mock', 'Mock'), ('other', 'Other')], max_length=32)),
                ('request_model', models.CharField(max_length=100)),
                ('response_model', models.CharField(blank=True, default='', max_length=100)),
                ('operation', models.CharField(default='chat', max_length=32)),
                ('is_streaming', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error'), ('aborted', 'Aborted')], default='pending', max_length=10)),
                ('error_type', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('first_chunk_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('ttft_ms', models.FloatField(blank=True, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('cached_tokens', models.IntegerField(blank=True, null=True)),
                ('reasoning_tokens', models.IntegerField(blank=True, null=True)),
                ('tokens_estimated', models.BooleanField(default=False)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('finish_reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('prompt_preview', models.TextField(blank=True, default='')),
                ('response_preview', models.TextField(blank=True, default='')),
                ('pii_masked', models.BooleanField(default=False)),
                ('pii_entities_found', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('environment', models.CharField(default='default', max_length=40)),
                ('sdk_release', models.CharField(blank=True, default='', max_length=40)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['session_id', 'started_at'], name='inflog_session_time'), models.Index(fields=['provider', 'request_model', 'started_at'], name='inflog_model_time'), models.Index(fields=['started_at'], name='inflog_time'), models.Index(condition=models.Q(('status', 'error')), fields=['started_at'], name='inflog_errors_time'), django.contrib.postgres.indexes.GinIndex(fields=['raw_metadata'], name='inflog_meta_gin', opclasses=['jsonb_path_ops'])],
            },
        ),
    ]
