# Generated by Django 5.2.17 on 2026-08-16 16:37

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inferencelog',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['started_at'], name='inflog_started_brin', pages_per_range=64),
        ),
    ]
