-- Argus — PostgreSQL schema (DDL)
--
-- Generated from the running database with:
--   docker compose exec -T postgres pg_dump -U argus --schema-only --no-owner --no-privileges argus
--
-- This file is the source of truth for review; the schema itself is created and
-- versioned by Django migrations (server/apps/*/migrations/), which is what runs
-- on deploy. Apply this DDL directly only when bootstrapping a database outside
-- the app (e.g. a managed Postgres provisioned by a DBA):
--   psql "$DATABASE_URL" -f db/schema.sql
--
-- Design notes for the telemetry table (rationale in docs/SCHEMA.md):
--   * ULID primary keys — time-ordered, so inserts stay at the right edge of the
--     B-tree instead of scattering random UUIDs across pages.
--   * generation_id UNIQUE — the idempotency key that makes at-least-once Kafka
--     delivery safe: replaying an event can never duplicate a row.
--   * Typed columns for everything filtered or aggregated (provider, model,
--     status, latency, tokens, cost); JSONB only for the open-ended tail.
--   * Composite indexes ordered to match the dashboard's access patterns, plus a
--     partial index on errors and a BRIN index on the append-only timestamp.
--   * timestamptz throughout (USE_TZ=True); all infrastructure runs in UTC.
--
SET default_tablespace = '';

SET default_table_access_method = heap;

-- Name: accounts_user; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(10) NOT NULL
);


-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: auth_group; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: chat_message; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.chat_message (
    id character varying(26) NOT NULL,
    role character varying(10) NOT NULL,
    content text NOT NULL,
    generation_id character varying(26),
    provider character varying(32) NOT NULL,
    model character varying(100) NOT NULL,
    seq integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    session_id character varying(26) NOT NULL,
    CONSTRAINT chat_message_seq_check CHECK ((seq >= 0))
);


-- Name: chat_session; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.chat_session (
    id character varying(26) NOT NULL,
    title character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id character varying(26),
    user_id bigint
);


-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- Name: django_session; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


-- Name: projects_project; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.projects_project (
    id character varying(26) NOT NULL,
    name character varying(100) NOT NULL,
    environment character varying(40) NOT NULL,
    key_hash character varying(64) NOT NULL,
    key_hint character varying(20) NOT NULL,
    key_rotated_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    monthly_budget_usd numeric(10,2)
);


-- Name: telemetry_inferencelog; Type: TABLE; Schema: public; Owner: -

CREATE TABLE public.telemetry_inferencelog (
    id character varying(26) NOT NULL,
    generation_id character varying(64) NOT NULL,
    session_id character varying(200) NOT NULL,
    trace_id character varying(64) NOT NULL,
    project_id character varying(26) NOT NULL,
    end_user_id character varying(128) NOT NULL,
    provider character varying(32) NOT NULL,
    request_model character varying(100) NOT NULL,
    response_model character varying(100) NOT NULL,
    operation character varying(32) NOT NULL,
    is_streaming boolean NOT NULL,
    status character varying(10) NOT NULL,
    error_type character varying(100) NOT NULL,
    error_message text NOT NULL,
    started_at timestamp with time zone NOT NULL,
    first_chunk_at timestamp with time zone,
    completed_at timestamp with time zone,
    latency_ms double precision,
    ttft_ms double precision,
    input_tokens integer,
    output_tokens integer,
    cached_tokens integer,
    reasoning_tokens integer,
    tokens_estimated boolean NOT NULL,
    cost_usd numeric(12,8),
    finish_reasons character varying(40)[] NOT NULL,
    request_params jsonb NOT NULL,
    prompt_preview text NOT NULL,
    response_preview text NOT NULL,
    pii_masked boolean NOT NULL,
    pii_entities_found character varying(40)[] NOT NULL,
    environment character varying(40) NOT NULL,
    sdk_release character varying(40) NOT NULL,
    raw_metadata jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


-- Name: chat_session chat_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_session
    ADD CONSTRAINT chat_session_pkey PRIMARY KEY (id);


-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


-- Name: projects_project projects_project_key_hash_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_key_hash_key UNIQUE (key_hash);


-- Name: projects_project projects_project_name_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_name_key UNIQUE (name);


-- Name: projects_project projects_project_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_pkey PRIMARY KEY (id);


-- Name: telemetry_inferencelog telemetry_inferencelog_generation_id_key; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.telemetry_inferencelog
    ADD CONSTRAINT telemetry_inferencelog_generation_id_key UNIQUE (generation_id);


-- Name: telemetry_inferencelog telemetry_inferencelog_pkey; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.telemetry_inferencelog
    ADD CONSTRAINT telemetry_inferencelog_pkey PRIMARY KEY (id);


-- Name: chat_message uniq_message_seq_per_session; Type: CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT uniq_message_seq_per_session UNIQUE (session_id, seq);


-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: -

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: -

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: -

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: -

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


-- Name: chat_message_id_23769959_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_message_id_23769959_like ON public.chat_message USING btree (id varchar_pattern_ops);


-- Name: chat_message_session_id_9abc6edf; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_message_session_id_9abc6edf ON public.chat_message USING btree (session_id);


-- Name: chat_message_session_id_9abc6edf_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_message_session_id_9abc6edf_like ON public.chat_message USING btree (session_id varchar_pattern_ops);


-- Name: chat_session_id_56002939_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_session_id_56002939_like ON public.chat_session USING btree (id varchar_pattern_ops);


-- Name: chat_session_project_id_e497ba95; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_session_project_id_e497ba95 ON public.chat_session USING btree (project_id);


-- Name: chat_session_project_id_e497ba95_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_session_project_id_e497ba95_like ON public.chat_session USING btree (project_id varchar_pattern_ops);


-- Name: chat_session_user_id_b860f903; Type: INDEX; Schema: public; Owner: -

CREATE INDEX chat_session_user_id_b860f903 ON public.chat_session USING btree (user_id);


-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


-- Name: inflog_errors_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX inflog_errors_time ON public.telemetry_inferencelog USING btree (started_at) WHERE ((status)::text = 'error'::text);


-- Name: inflog_meta_gin; Type: INDEX; Schema: public; Owner: -

CREATE INDEX inflog_meta_gin ON public.telemetry_inferencelog USING gin (raw_metadata jsonb_path_ops);


-- Name: inflog_model_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX inflog_model_time ON public.telemetry_inferencelog USING btree (provider, request_model, started_at);


-- Name: inflog_session_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX inflog_session_time ON public.telemetry_inferencelog USING btree (session_id, started_at);


-- Name: inflog_started_brin; Type: INDEX; Schema: public; Owner: -

CREATE INDEX inflog_started_brin ON public.telemetry_inferencelog USING brin (started_at) WITH (pages_per_range='64');


-- Name: inflog_time; Type: INDEX; Schema: public; Owner: -

CREATE INDEX inflog_time ON public.telemetry_inferencelog USING btree (started_at);


-- Name: projects_project_created_by_id_c49d7b6d; Type: INDEX; Schema: public; Owner: -

CREATE INDEX projects_project_created_by_id_c49d7b6d ON public.projects_project USING btree (created_by_id);


-- Name: projects_project_id_12b5a625_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX projects_project_id_12b5a625_like ON public.projects_project USING btree (id varchar_pattern_ops);


-- Name: projects_project_key_hash_54a820bf_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX projects_project_key_hash_54a820bf_like ON public.projects_project USING btree (key_hash varchar_pattern_ops);


-- Name: projects_project_name_1ecf4961_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX projects_project_name_1ecf4961_like ON public.projects_project USING btree (name varchar_pattern_ops);


-- Name: telemetry_inferencelog_generation_id_e498802a_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX telemetry_inferencelog_generation_id_e498802a_like ON public.telemetry_inferencelog USING btree (generation_id varchar_pattern_ops);


-- Name: telemetry_inferencelog_id_556b8a34_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX telemetry_inferencelog_id_556b8a34_like ON public.telemetry_inferencelog USING btree (id varchar_pattern_ops);


-- Name: telemetry_inferencelog_project_id_fb9b8cee; Type: INDEX; Schema: public; Owner: -

CREATE INDEX telemetry_inferencelog_project_id_fb9b8cee ON public.telemetry_inferencelog USING btree (project_id);


-- Name: telemetry_inferencelog_project_id_fb9b8cee_like; Type: INDEX; Schema: public; Owner: -

CREATE INDEX telemetry_inferencelog_project_id_fb9b8cee_like ON public.telemetry_inferencelog USING btree (project_id varchar_pattern_ops);


-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: chat_message chat_message_session_id_9abc6edf_fk_chat_session_id; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_session_id_9abc6edf_fk_chat_session_id FOREIGN KEY (session_id) REFERENCES public.chat_session(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: chat_session chat_session_project_id_e497ba95_fk_projects_project_id; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_session
    ADD CONSTRAINT chat_session_project_id_e497ba95_fk_projects_project_id FOREIGN KEY (project_id) REFERENCES public.projects_project(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: chat_session chat_session_user_id_b860f903_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.chat_session
    ADD CONSTRAINT chat_session_user_id_b860f903_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Name: projects_project projects_project_created_by_id_c49d7b6d_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -

ALTER TABLE ONLY public.projects_project
    ADD CONSTRAINT projects_project_created_by_id_c49d7b6d_fk_accounts_user_id FOREIGN KEY (created_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


-- PostgreSQL database dump complete


